name: slack-approval
description: Custom action to send approval request to Slack from GitHub Actions
author: Beom
runs:
  using: "node20"
  main: "dist/index.js"
branding:
  icon: plus
  color: green

inputs:
  baseMessageTs:
    description: target message ts
  approvers:
    description: "A comma-separated list of approvers' slack user ids"
    required: true
    default: ""
  minimumApprovalCount:
    description: "The minimum number of approvals required"
    required: false
    default: "1"
  baseMessageBlocks:
    description: "The title of the message indicating approval is needed"
    required: false
  successMessageBlocks:
    description: "The message body indicating approval is pending"
    required: false
  failMessageBlocks:
    description: "The message body indicating approval has been rejected"
    required: false

outputs:
  mainMessageTs:
    description: slack main message ts
  replyMessageTs:
    description: slack reply message ts
  
  