name: Test slack-approval

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  workflow_dispatch:

jobs:
  approval:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: |
          npm install

      - name: slack-approval
        id: approval
        uses: ./
        env:
          SLACK_APP_TOKEN: ${{ secrets.SLACK_APP_TOKEN }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_SIGNING_SECRET: ${{ secrets.SLACK_SIGNING_SECRET }}
          SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
        with:
          approvers: U07U2EYRBGD,user2
          minimumApprovalCount: 1
          baseMessagePayload: |
            {
              "text": "base messaage approve reuqest"
            }
          successMessagePayload: |
            {
              "text": "success messaage approve reuqest"
            }
          failMessagePayload: |
            {
              "text": "fail messaage approve reuqest"
            }
        timeout-minutes: 60
      - name: output test
        run: |
          echo "${{ steps.approval.outputs.mainMessageTs }} ${{steps.approval.outputs.replyMessageTs }}"
